// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofkakwegddildjrstick.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ma2Frd2VnZGRpbGRqcnN0aWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDU0MTgsImV4cCI6MjA2MzY4MTQxOH0.JKcq31-OHPlvIwHX47Pei8vwpDk2tDLbi6fsNl_vhqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);